### ISSUE TITLE
Directory not writeable by webserver

### ISSUE THREAD

**Issue by ghost** [ndeet/unzipper#19]
Hi. I try to use this script on my server but i get the error message "Directory not writeable by web server"

**Comment by ndeet** [comment]
Hi,

this is a problem with the file system configuration and not related to the script.

a) if you use the script on your hosters webspace, contact them why the PHP script can't write data onto the filesystem. (this happens if webserver is configured with mod_php but file system has different ownership)

b) if on your own server/machine make sure the file system has the same ownership as the webserver for Debian/Ubuntu this is likely www-data; intro about `chown` and permissions eg. [here](https://www.hostingadvice.com/how-to/change-file-ownershipgroups-linux/)
