### ISSUE TITLE
Memory limit when unzipping large files

### ISSUE THREAD

**Issue by rospus** [ndeet/unzipper#7]
Hi Andreas, first of all thanks for your script. I used it today for unzipping a very large file (343 Mb) on a shared hosting server getting issues probably due to the low memory available for PHP processes.
The GUI gave a succees message, but not all files were unzipped (about 15k).
If my speculations aren't wrong (I'm not a real developer) I believe that if unzipping would be done in chunks probably also big files in low memory environments could be unzipped succesfully.
A similar problem was discussed and solved in this stackexchange thread:
 [https://stackoverflow.com/questions/3263129/un](url)

**Comment by ndeet** [comment]
Hi Alessandro,

thanks for reporting back. Are you sure you are hitting the memory limit? I tried to reproduce and force a memory limit error. But even with only 8 MB I was able to unzip a 150 MB (380MB unzipped) archive with 20k files inside. (tested with PHP 7.0.20)

Also if you run into memory limit you will get a blank page or an fatal error message. You won't get any success message in the GUI. Another thing which can be a problem is the max_execution_time setting, but also there the script will abort and give you a blank page or some error.

Did you try to unzip this archive locally with an unzip program so that you see if the files are also missing there (maybe corrupted archive?).

Do you get any error message in the logs? If not, maybe your phpinfo() output helps or if there is no sensitive data you can provide me the .zip.

**Comment by ndeet** [comment]
FYI, tested now with 8MB memory_limit and 1.14 GB file without a problem.

**Comment by ndeet** [comment]
Closing because no response and not reproducible.

**Comment by rospus** [comment]
Hi Andreas, I didn't follow up as probably the issue is due to a
combination of hosting server's settings that is not worth to deepen.
I also couldn't replicate the problem locally at that time, sorry for not
letting you know.

Alessandro

Il ven 5 gen 2018, 13:33 Andreas Tasch <notifications@github.com> ha
scritto:

**Comment by ndeet** [comment]
Hi Alessandro,
thanks for coming back, no worries. Glad you resolved it.
